#!/usr/bin/env bash
HOOKS_PATH=$(dirname $0)

ERRORS=0

# lint Python files
$HOOKS_PATH/style/py_flake8.sh
let ERRORS=$ERRORS+$?

# lintr on R files
$HOOKS_PATH/style/r_lintr.sh
let ERRORS=$ERRORS+$?

exit $ERRORS