trigger:
  branches:
    include:
      - main
      - master
      - hotfix*

pr:
  branches:
    include:
      - main
      - master
      - hotfix*
 

pool:
  name: "ch-mg-ue2-agent-pool-mdp001"
  demands:
    - agent.os -equals Linux
    - ImageOverride -equals ubuntu-22.04-covera-build


parameters:
  - name: pythonVersion
    type: string
    default: "3.11.7"

jobs:
  - job: build
    displayName: "Build and Test with spreemohealth/style-tests"
    
    variables:
      TZ: 'America/New_York'

    steps:
      - task: Bash@3
        displayName: 'Set timezone'
        inputs:
          targetType: 'inline'
          script: |
            sudo ln -snf /usr/share/zoneinfo/$(TZ) /etc/localtime && echo $(TZ) | sudo tee /etc/timezone

      - checkout: self

      - task: UsePythonVersion@0
        inputs:
          versionSpec: "${{ parameters.pythonVersion }}"

      - script: |
          python -m venv pythonenv
          source pythonenv/bin/activate
          pip install --upgrade pip
          pip install flake8 gitpython
        displayName: 'Install Python libraries'

      - script: |
          source pythonenv/bin/activate
          export PATH="$HOME/.local/bin:$PATH"
          python -m flake8 ./
        displayName: 'Run flake8'

      - script: |
          sudo apt install nodejs npm r-base -y
        displayName: 'Instal npm and markdownlint'

      - task: UseNode@1
        inputs:
          version: '18.x'
        displayName: 'Use Node.js 18'

      - script: |
          sudo npm install -g markdownlint-cli
        displayName: 'Instal npm and markdownlint'

      - script: |
          markdownlint ./
        displayName: 'Lint Markdown code'

      - script: |
          source pythonenv/bin/activate
          rm -R .git
          python -m unittest discover -s ./tests -v
        displayName: 'Run tests'
