trigger:
  branches:
    include:
      - main
      - master
      - hotfix*

pr:
  branches:
    include:
      - main
      - master
      - hotfix*

pool:
  name: "ch-mg-ue2-agent-pool-mdp001"
  demands:
    - agent.os -equals Linux
    - ImageOverride -equals ubuntu-22.04-covera-build

variables:
  - group: covera-build
  - name: CODE_COVERAGE_TARGET_PERCENTAGE
    value: "0"
  - name: CRITICAL_VULNERABILITY_THRESHOLD_COUNT
    value: "0"
  - name: PROJECT_NAME
    value: "style"
  - name: IMAGE_DEFAULT_TAG
    value: "2.2.1"
  - name: PUBLISH_BRANCH
    value: $[ coalesce(variables['UI_PUBLISH_BRANCH'], 'refs/heads/main') ]
  - name: AZURE_STORAGE_ACCOUNT
    value: 'myrtusdevopsmodelsst'
  - name: AZURE_STORAGE_CONTAINER
    value: 'testing-container-ai'
    
  - name: PUBLISH_JFROG
    value: false  

parameters:
  - name: pythonVersion
    type: string
    default: "3.10.12"
  - name: appDeploymentsBranch
    type: string
    default: "refs/heads/main"

resources:
  repositories:
    - repository: azureDevOpsTemplates
      type: github
      name: coverahealth/app-deployments
      ref: "${{ parameters.appDeploymentsBranch }}"
      endpoint: coverahealth

stages:
  - stage: BuildAndTest
    displayName: "Build and Test"
    jobs:
      - job: Install_Test_Build
        displayName: "Build and Test"
        variables:
          shouldPublishPipelineArtifacts: or(eq(variables['Build.SourceBranch'], variables['PUBLISH_BRANCH']), eq(variables['Build.SourceBranch'], 'refs/heads/master'), startsWith(variables['Build.SourceBranch'], 'refs/heads/hotfix'))
        steps:
          - checkout: self
            fetchDepth: 0
          
          - template: azure-devops-templates/download-setup-production-models-template.yaml@azureDevOpsTemplates
            parameters:
              azureClientId: $(AZURE_CLIENT_ID)
              azureClientSecret: $(AZURE_CLIENT_SECRET)
              azureTenantId: $(AZURE_TENANT_ID)
              subscriptionName: $(AZURE_SUBSCRIPTION_NAME)
              azureStorageAccount: $(AZURE_STORAGE_ACCOUNT)
              azureStorageContainer: $(AZURE_STORAGE_CONTAINER)

          - template: azure-devops-templates/docker-build-test-and-scan-template.yaml@azureDevOpsTemplates
            parameters:
              pythonVersion: "${{ parameters.pythonVersion }}"
              codeCoverageThreshold: "$(CODE_COVERAGE_TARGET_PERCENTAGE)"
              pipelineArtifactsPath: "dist"
              runTests: false
              containerRegistry: $(CONTAINER_REGISTRY_SERVICE_CONNECTION)
              projectName: "$(PROJECT_NAME)"
              dockerRegistry: $(ACR_URL)
              imageDefaultTag: "$(IMAGE_DEFAULT_TAG)"
              dockerScanVulnerabilityThreshold: "$(CRITICAL_VULNERABILITY_THRESHOLD_COUNT)"
              shouldPublishPipelineArtifacts: ${{ variables.shouldPublishPipelineArtifacts }}

  - stage: PushToRepository
    displayName: Push Docker image to ACR
    dependsOn: BuildAndTest
    condition: and(succeeded(), or(eq(variables['Build.SourceBranch'], variables['PUBLISH_BRANCH']), eq(variables['Build.SourceBranch'], 'refs/heads/master'), startsWith(variables['Build.SourceBranch'], 'refs/heads/hotfix')))
    variables:
      buildTsTag: $[stageDependencies.BuildAndTest.Install_Test_Build.outputs['SetBuildTsTag.BUILD_TS_TAG']]
    jobs:
      - template: azure-devops-templates/docker-multiple-push-template.yaml@azureDevOpsTemplates
        parameters:
          projectName: "$(PROJECT_NAME)"
          containerRegistry: $(CONTAINER_REGISTRY_SERVICE_CONNECTION)
          acrRegistryUrl: "$(ACR_URL)"
          imageTag: "$(IMAGE_DEFAULT_TAG)"
          buildTsTag: "$(buildTsTag)"
        