#!/usr/bin/env python3
import sys

from style.pre_commit.git import GitHandle
from style.pre_commit.lint import Lint

# set no traceback in error messages
sys.tracebacklimit = 0

sys.exit(
    Lint(GitHandle()).run()
)
